---
abstract: 'Perl bindings for Kerberos libraries'
author:
  - 'Russ Allbery <rra@cpan.org>'
build_requires:
  ExtUtils::CBuilder: '0'
configure_requires:
  Config::AutoConf: '0'
  IPC::System::Simple: '0'
  Module::Build: '0.3604'
  autodie: '0'
  perl: '5.010'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Authen-Kerberos
provides:
  Authen::Kerberos:
    file: lib/Authen/Kerberos.pm
    version: '0.03'
  Authen::Kerberos::Exception:
    file: lib/Authen/Kerberos/Exception.pm
    version: '0.03'
  Authen::Kerberos::Kadmin:
    file: lib/Authen/Kerberos/Kadmin.pm
    version: '0.03'
  Authen::Kerberos::Kadmin::Entry:
    file: lib/Authen/Kerberos/Kadmin/Entry.pm
    version: '0.03'
  Authen::Kerberos::Keytab:
    file: lib/Authen/Kerberos/Keytab.pm
    version: '0.03'
  Authen::Kerberos::KeytabEntry:
    file: lib/Authen/Kerberos/KeytabEntry.pm
    version: '0.03'
  Authen::Kerberos::Principal:
    file: lib/Authen/Kerberos/Principal.pm
    version: '0.03'
requires:
  autodie: '0'
  perl: '5.010'
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: '0.03'
